services:
  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/hub
    environment:
      - POSTGRES_DB=hub
      - POSTGRES_USER=hub_admin
      - POSTGRES_PASSWORD=hub_admin_123
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hub
      - POSTGRES_USER=hub_admin
      - POSTGRES_PASSWORD=hub_admin_123
  