services:
  backend:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && python manage.py makemigrations && python manage.py migrate"
    volumes:
      - .:/hub
    ports:
      - "8000:8000"
  